"""empty message

Revision ID: 29f6caf2090d
Revises: 
Create Date: 2023-10-12 11:04:46.635007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f6caf2090d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bakeries_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cakes_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cake_bakeries_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cake_id', sa.Integer(), nullable=False),
    sa.Column('bakery_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bakery_id'], ['bakeries_table.id'], name=op.f('fk_cake_bakeries_table_bakery_id_bakeries_table')),
    sa.ForeignKeyConstraint(['cake_id'], ['cakes_table.id'], name=op.f('fk_cake_bakeries_table_cake_id_cakes_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cake_bakeries_table')
    op.drop_table('cakes_table')
    op.drop_table('bakeries_table')
    # ### end Alembic commands ###
